### ISSUE TITLE
Task 7 - Begin CRF on CRAFT

### ISSUE THREAD

**Issue by jelly-borges** [jelly-borges/Sequence2SequenceRotation#10]
**Goal for Friday** - Run CRF on one document/one ontology
**Goal for end of week** - Run CRF on 50/50 hold out set case for one ontology

**End of rotation** -
1. by algorithm
a. CRF
b. TBD
2. by test/train ratio case (categories tentative upon further research)
a. 60 train 7 test (~9:1)
b. 33 train 34 test (~1:1)
c. 20 train 57 test (~1:3)
3. by document

**Comment by mboguslav** [comment]
Good start with the CRF. Make sure to fully understand the code when implementing it. If you manipulate it a bit that can help as you showed me in the sentenceGetter function.
